### ISSUE TITLE
Red Drone Color

### ISSUE THREAD

**Issue by p4n0p71c0n** [RWDevathon/Android-Tiers-Reforged#12]
Drones are spawned with a default red color. I'm unsure if this is due to an interaction between this mod and the Character Editor mod.

There also appears to be no way to start a colony with Androids only. Androids need to be included as parts in the space ship wreck.

**Comment by RWDevathon** [comment]
Androids will spawn with a random color normally. Character Editor is working fine with my tests, and you can use it to manually change their paint colors just fine. Note that there is no current method for repainting androids otherwise.

The default Android scenario that comes with the mod is the only one where androids will appear as part of a starting group. The scenario always picks T2 androids for starting pawns if you use it.

**Comment by p4n0p71c0n** [comment]
Is it be possible to hard code a consistent default color?

 I would also request more support for custom start scenarios. Why stop there with the customisation?

**Comment by p4n0p71c0n** [comment]
Perhaps a default color option of white. I know it's silly but this made the pawns look nice.

Also why stop with just the possibilities of the scenario? You could provide more support for custom starting scenarios.

**Comment by lazycooken** [comment]
You can also make your own scenarios, that a abilty provided by the game.

-------- Original Message --------
On Dec 27, 2022, 2:44 PM, p4n0p71c0n < ***@***.***> wrote:
Perhaps a default color option of white. I know it's silly but this made the pawns look nice.
Also why stop with just the possibilities of the scenario? You could provide more support for custom starting scenarios.

**Comment by p4n0p71c0n** [comment]
> You can also make your own scenarios, that a abilty provided by the game.
> […](#)
> -------- Original Message -------- On Dec 27, 2022, 2:44 PM, p4n0p71c0n < ***@***.***> wrote: Perhaps a default color option of white. I know it's silly but this made the pawns look nice. Also why stop with just the possibilities of the scenario? You could provide more support for custom starting scenarios.

That was what I was asking for support for...you aren't able to select them.

**Comment by RWDevathon** [comment]
Ah I forgot to mention that a method for painting androids is planned, just not available yet. I can't force them to spawn a particular color because of RimWorld's very picky pawn generation for random pawns, but I can allow players to repaint androids in some cases and allow players to pick the colors of newly constructed androids.

All in due time.

**Comment by p4n0p71c0n** [comment]
> Ah I forgot to mention that a method for painting androids is planned, just not available yet. I can't force them to spawn a particular color because of RimWorld's very picky pawn generation for random pawns, but I can allow players to repaint androids in some cases and allow players to pick the colors of newly constructed androids.
> 
> All in due time.

Perfect.

Could you also confirm if it would be possible to include more options for creating scenarios in the future?

**Comment by RWDevathon** [comment]
I'm not entirely sure what you mean here. Scenario creation is already highly customizable and straightforward.

**Comment by RWDevathon** [comment]
Recent pushes to the main branch include the possibility to repaint androids. As such, the primary issue here has been resolved.
