### ISSUE TITLE
Cannot capture enemy android.

### ISSUE THREAD

**Issue by jinks** [RWDevathon/Android-Tiers-Reforged#9]
Playing on Dev1.4 commit fe21c170219efd36bf38ee72cc5ee1e54c6169c5

I Downed an android in a raid, but I can't seem to capture them.
I have a working prison with a human already in it. I tried so far a normal bed, a bed with a bedside charger and a charging pod, all inside the prison and marked for prisoners but the game keeps complaining that there is no valid free bed.

**Comment by RWDevathon** [comment]
This problem should be resolved with the next series of pushes, either within the next ~4 hours or some time tomorrow.

It's part of a larger issue with charging vs. non-charging beds that needs to be resolved at a higher level.

**Comment by jinks** [comment]
Another one I've just noticed is that the slave tab doesn't work on robots (t1) because they have no `terror` stat.

Good to see all of this is moving along. So excited for the end result. :)

**Comment by RWDevathon** [comment]
Sorry for the late response. The most recent (experimental) push to the 1.4 DevTest branch should resolve this issue as there is no longer a restriction on what beds are valid for mechanical units to be taken to. Do note that this means they can take non-charge-capable beds, although they will always try to locate one when they need to.

If the issue is solved with the latest push, please close this issue (or I'll do it in a few days).

As for your T1 slave-related issue, can you open a new issue with that if it is not resolved in the newest push?

**Comment by jinks** [comment]
> Sorry for the late response.

Don't worry about it. You're doing this for free and I expect to play many more years of Rimworld, so it'll be done when it's done.

Capturing a downed drone now works as expected.
